### ISSUE TITLE
Not able to give width or height as viewport height or percentage in glide components props

### ISSUE THREAD

**Issue by kishanjasani** [andrewangelle/react-glide#19]

**Comment by andrewangelle** [comment]
@kishanjasani Can you elaborate? Is the issue that the type definition doesn't allow a string or is the issue that the height and width aren't getting applied in the browser?

This line likely needs to be changed to `number | string`. 
https://github.com/andrewangelle/react-glide/blob/master/src/types.ts#L24

If you feel like tossing up another PR. I'll accept it.

**Comment by kishanjasani** [comment]
@andrewangelle  The issue is that the type definition doesn't allow a string. like I am not able to add height and width like `100vh or 100%`. I don't have much knowledge of typescript. It will be better if we can add something like `number | string` instead of just `number`.

**Comment by andrewangelle** [comment]
fixed in 4.0.0
