### ISSUE TITLE
Button styles are set with global scope

### ISSUE THREAD

**Issue by mvallejo3** [andrewangelle/react-glide#30]
Button styles should be declared within the `.glide--carousel` scope. Instead they are declared globally. This messes up with the styles of all buttons in the page. Not great practice.

instead of setting the button styles as `button` they should be set as `.glide--container button`. This will prevent the buttons styles for the carousel from affecting other buttons on the page.

**Comment by andrewangelle** [comment]
fixed in 3.2.1
